# Generated by Django 2.1.5 on 2019-03-07 12:59

import clientbase.upload_photo
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('date_of_birth', models.DateField()),
                ('photo', models.ImageField(upload_to=clientbase.upload_photo.UploadPhoto('photo'))),
                ('likes', models.IntegerField(default=0)),
            ],
        ),
    ]
