# Generated by Django 2.1.5 on 2019-03-25 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('celeryapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='productdata',
            name='errors',
            field=models.CharField(blank=True, max_length=100000),
        ),
    ]
