# Generated by Django 2.1.5 on 2019-03-28 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('celeryapp', '0002_productdata_errors'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productdata',
            name='errors',
            field=models.FileField(blank=True, upload_to='logs'),
        ),
    ]
